"""Add cascade delete

Revision ID: 6bec3c39b99a
Revises: d41350663592
Create Date: 2022-09-15 19:32:28.939971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec3c39b99a'
down_revision = 'd41350663592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__files__parent_id__files', 'files', type_='foreignkey')
    op.create_foreign_key(op.f('fk__files__parent_id__files'), 'files', 'files', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__files__parent_id__files'), 'files', type_='foreignkey')
    op.create_foreign_key('fk__files__parent_id__files', 'files', 'files', ['parent_id'], ['id'])
    # ### end Alembic commands ###
